export enum ShoppingListActionTypes {
  ADD_INGREDIENT = "[SHOPPING LIST] ADD_INGREDIENT",
  ADD_INGREDIENTS = "[SHOPPING LIST] ADD_INGREDIENTS",
  UPDATE_INGREDIENT = "[SHOPPING LIST] UPDATE_INGREDIENT",
  DELETE_INGREDIENT = "[SHOPPING LIST] DELETE_INGREDIENT",
  START_EDIT = "[SHOPPING LIST] START_EDIT",
  STOP_EDIT = "[SHOPPING LIST] STOP_EDIT"
};

export enum AuthActionTypes {
  LOGIN_START = "[AUTH] LOGIN_START",
  AUTHENTICATE_SUCCESS = "[AUTH] AUTHENTICATE_SUCCESS",
  AUTHENTICATE_FAIL = "[AUTH] AUTHENTICATE_FAIL",
  SIGNUP_START = "[AUTH] SIGNUP_START",
  CLEAR_ERROR = "[AUTH] CLEAR_ERROR",
  LOGOUT = "[AUTH] LOGOUT",
  AUTO_LOGIN = "[AUTH] AUTO_LOGIN"
};

export enum RecipeActionTypes {
  SET_RECIPES = "[RECIPES] SET_RECIPES",
  FETCH_RECIPES = "[RECIPES] FETCH_RECIPES",
  ADD_RECIPE = "[RECIPES] ADD_RECIPE",
  UPDATE_RECIPE = "[RECIPES] UPDATE_RECIPE",
  DELETE_RECIPE = "[RECIPES] DELETE_RECIPE",
  SAVE_RECIPES = "[RECIPES] SAVE_RECIPES"
}